-- ==========================================
-- Inkhaven WebRTC Auto-Cleanup Job
-- ==========================================
-- Requires 'pg_cron' extension to be enabled in Supabase Database settings.

-- 1. Enable pg_cron (if not already enabled)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- 2. Create the cleanup function
CREATE OR REPLACE FUNCTION delete_old_messages()
RETURNS void AS $$
BEGIN
  -- Delete all messages older than 24 hours
  DELETE FROM public.messages
  WHERE created_at < NOW() - INTERVAL '24 hours';
  
  -- Optionally delete old orphaned rooms as well since they are now UUIDs generated by WebRTC
  DELETE FROM public.rooms
  WHERE created_at < NOW() - INTERVAL '24 hours';
END;
$$ LANGUAGE plpgsql;

-- 3. Schedule the cron job to run every hour at minute 0
SELECT cron.schedule(
    'delete-old-messages-job', 
    '0 * * * *', 
    $$SELECT delete_old_messages()$$
);

/*
To verify it's scheduled:
SELECT * FROM cron.job;

To unschedule if needed:
SELECT cron.unschedule('delete-old-messages-job');
*/
